---
name: Node.js
"on":
  pull_request:
  push:
    branches: [main]

env:
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "microsoft"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: okhiroyuki/composite-actions
          path: ./.github/actions/composite-actions
      - uses: ./.github/actions/composite-actions/setup-node
      - name: npm test
        run: npm test --if-present
        env:
          CI: true
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: okhiroyuki/composite-actions
          path: ./.github/actions/composite-actions
      - uses: ./.github/actions/composite-actions/setup-node
      - name: set up JDK
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4
        with:
          distribution: ${{env.JAVA_DISTRIBUTION}}
          java-version: ${{env.JAVA_VERSION}}
      - name: npm run build
        run: |
          npm run build --if-present
        env:
          CI: true
